/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:9b28c08e-9947-45ed-927e-0c329fac8d14",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_Cnm9vBisu",
    "aws_user_pools_web_client_id": "3719o6qjbpsnfdk6alafca8g4h",
    "oauth": {
        "domain": "simplysayfe-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.simplysay.co/home/",
        "redirectSignOut": "https://dev.simplysay.co/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "simplysayfe-dev",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "https://d234a6ggdwrty0.cloudfront.net"
};

export default awsmobile;
